/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connectai;

import javax.swing.*;
import java.awt.*;
import java.lang.reflect.Field;

/**
 *
 * @author dominic.cousins
 */
public class GUI extends javax.swing.JFrame {

    private ConnectAI controller;
    
    /**
     * Creates new form GUI
     */
    public GUI(ConnectAI thread) {
        initComponents();
        controller = thread;
    }

    //function to return the object with given name
    @SuppressWarnings("Unchecked")
    public <T extends Component> T getComponentByName(String name)
    {
        for(Field field : this.getClass().getDeclaredFields())
        {
            try
            {
                field.setAccessible(true);
                if(name.equals(field.getName()))
                {
                    final Object potentialMatch = field.get(this);
                    return (T) potentialMatch;
                }
            }
            catch(SecurityException | IllegalArgumentException |IllegalAccessException ex)
            {
                System.out.println("ERROR in getComponentByName(" + name + ") : " + ex);
            }
        }
        
        return null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tile04 = new javax.swing.JPanel();
        tile05 = new javax.swing.JPanel();
        tile03 = new javax.swing.JPanel();
        tile02 = new javax.swing.JPanel();
        tile01 = new javax.swing.JPanel();
        tile15 = new javax.swing.JPanel();
        tile14 = new javax.swing.JPanel();
        tile13 = new javax.swing.JPanel();
        tile12 = new javax.swing.JPanel();
        tile11 = new javax.swing.JPanel();
        tile10 = new javax.swing.JPanel();
        tile25 = new javax.swing.JPanel();
        tile24 = new javax.swing.JPanel();
        tile23 = new javax.swing.JPanel();
        tile22 = new javax.swing.JPanel();
        tile21 = new javax.swing.JPanel();
        tile20 = new javax.swing.JPanel();
        tile35 = new javax.swing.JPanel();
        tile34 = new javax.swing.JPanel();
        tile33 = new javax.swing.JPanel();
        tile32 = new javax.swing.JPanel();
        tile31 = new javax.swing.JPanel();
        tile30 = new javax.swing.JPanel();
        tile45 = new javax.swing.JPanel();
        tile43 = new javax.swing.JPanel();
        tile41 = new javax.swing.JPanel();
        tile40 = new javax.swing.JPanel();
        tile44 = new javax.swing.JPanel();
        tile42 = new javax.swing.JPanel();
        tile55 = new javax.swing.JPanel();
        tile53 = new javax.swing.JPanel();
        tile51 = new javax.swing.JPanel();
        tile50 = new javax.swing.JPanel();
        tile54 = new javax.swing.JPanel();
        tile52 = new javax.swing.JPanel();
        tile60 = new javax.swing.JPanel();
        tile63 = new javax.swing.JPanel();
        tile64 = new javax.swing.JPanel();
        tile65 = new javax.swing.JPanel();
        tile61 = new javax.swing.JPanel();
        tile62 = new javax.swing.JPanel();
        p1Name = new javax.swing.JLabel();
        p2Name = new javax.swing.JLabel();
        p1Score = new javax.swing.JLabel();
        p2Score = new javax.swing.JLabel();
        tile00 = new javax.swing.JPanel();
        play0 = new javax.swing.JButton();
        play1 = new javax.swing.JButton();
        play2 = new javax.swing.JButton();
        play3 = new javax.swing.JButton();
        play4 = new javax.swing.JButton();
        play5 = new javax.swing.JButton();
        play6 = new javax.swing.JButton();
        p1Score1 = new javax.swing.JLabel();
        p1Score2 = new javax.swing.JLabel();
        CPU1 = new javax.swing.JCheckBox();
        CPU2 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        p1Score3 = new javax.swing.JLabel();
        cpuThink = new javax.swing.JTextField();
        cpuIterations = new javax.swing.JTextField();
        p1Score4 = new javax.swing.JLabel();
        p1Score5 = new javax.swing.JLabel();
        Random2 = new javax.swing.JCheckBox();
        Random1 = new javax.swing.JCheckBox();
        p1Score6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 153));
        setPreferredSize(new java.awt.Dimension(900, 711));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        tile04.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile04Layout = new javax.swing.GroupLayout(tile04);
        tile04.setLayout(tile04Layout);
        tile04Layout.setHorizontalGroup(
            tile04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile04Layout.setVerticalGroup(
            tile04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile05.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile05Layout = new javax.swing.GroupLayout(tile05);
        tile05.setLayout(tile05Layout);
        tile05Layout.setHorizontalGroup(
            tile05Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile05Layout.setVerticalGroup(
            tile05Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile03.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile03Layout = new javax.swing.GroupLayout(tile03);
        tile03.setLayout(tile03Layout);
        tile03Layout.setHorizontalGroup(
            tile03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile03Layout.setVerticalGroup(
            tile03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile02.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile02Layout = new javax.swing.GroupLayout(tile02);
        tile02.setLayout(tile02Layout);
        tile02Layout.setHorizontalGroup(
            tile02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile02Layout.setVerticalGroup(
            tile02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile01.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile01Layout = new javax.swing.GroupLayout(tile01);
        tile01.setLayout(tile01Layout);
        tile01Layout.setHorizontalGroup(
            tile01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile01Layout.setVerticalGroup(
            tile01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile15.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile15Layout = new javax.swing.GroupLayout(tile15);
        tile15.setLayout(tile15Layout);
        tile15Layout.setHorizontalGroup(
            tile15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile15Layout.setVerticalGroup(
            tile15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile14.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile14Layout = new javax.swing.GroupLayout(tile14);
        tile14.setLayout(tile14Layout);
        tile14Layout.setHorizontalGroup(
            tile14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile14Layout.setVerticalGroup(
            tile14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile13.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile13Layout = new javax.swing.GroupLayout(tile13);
        tile13.setLayout(tile13Layout);
        tile13Layout.setHorizontalGroup(
            tile13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile13Layout.setVerticalGroup(
            tile13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile12.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile12Layout = new javax.swing.GroupLayout(tile12);
        tile12.setLayout(tile12Layout);
        tile12Layout.setHorizontalGroup(
            tile12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile12Layout.setVerticalGroup(
            tile12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile11.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile11Layout = new javax.swing.GroupLayout(tile11);
        tile11.setLayout(tile11Layout);
        tile11Layout.setHorizontalGroup(
            tile11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile11Layout.setVerticalGroup(
            tile11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile10.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile10Layout = new javax.swing.GroupLayout(tile10);
        tile10.setLayout(tile10Layout);
        tile10Layout.setHorizontalGroup(
            tile10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile10Layout.setVerticalGroup(
            tile10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile25.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile25Layout = new javax.swing.GroupLayout(tile25);
        tile25.setLayout(tile25Layout);
        tile25Layout.setHorizontalGroup(
            tile25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile25Layout.setVerticalGroup(
            tile25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile24.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile24Layout = new javax.swing.GroupLayout(tile24);
        tile24.setLayout(tile24Layout);
        tile24Layout.setHorizontalGroup(
            tile24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile24Layout.setVerticalGroup(
            tile24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile23.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile23Layout = new javax.swing.GroupLayout(tile23);
        tile23.setLayout(tile23Layout);
        tile23Layout.setHorizontalGroup(
            tile23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile23Layout.setVerticalGroup(
            tile23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile22.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile22Layout = new javax.swing.GroupLayout(tile22);
        tile22.setLayout(tile22Layout);
        tile22Layout.setHorizontalGroup(
            tile22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile22Layout.setVerticalGroup(
            tile22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile21.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile21Layout = new javax.swing.GroupLayout(tile21);
        tile21.setLayout(tile21Layout);
        tile21Layout.setHorizontalGroup(
            tile21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile21Layout.setVerticalGroup(
            tile21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile20.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile20Layout = new javax.swing.GroupLayout(tile20);
        tile20.setLayout(tile20Layout);
        tile20Layout.setHorizontalGroup(
            tile20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile20Layout.setVerticalGroup(
            tile20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile35.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile35Layout = new javax.swing.GroupLayout(tile35);
        tile35.setLayout(tile35Layout);
        tile35Layout.setHorizontalGroup(
            tile35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile35Layout.setVerticalGroup(
            tile35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile34.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile34Layout = new javax.swing.GroupLayout(tile34);
        tile34.setLayout(tile34Layout);
        tile34Layout.setHorizontalGroup(
            tile34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile34Layout.setVerticalGroup(
            tile34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile33.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile33Layout = new javax.swing.GroupLayout(tile33);
        tile33.setLayout(tile33Layout);
        tile33Layout.setHorizontalGroup(
            tile33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile33Layout.setVerticalGroup(
            tile33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile32.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile32Layout = new javax.swing.GroupLayout(tile32);
        tile32.setLayout(tile32Layout);
        tile32Layout.setHorizontalGroup(
            tile32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile32Layout.setVerticalGroup(
            tile32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile31.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile31Layout = new javax.swing.GroupLayout(tile31);
        tile31.setLayout(tile31Layout);
        tile31Layout.setHorizontalGroup(
            tile31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile31Layout.setVerticalGroup(
            tile31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile30.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile30Layout = new javax.swing.GroupLayout(tile30);
        tile30.setLayout(tile30Layout);
        tile30Layout.setHorizontalGroup(
            tile30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile30Layout.setVerticalGroup(
            tile30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile45.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile45Layout = new javax.swing.GroupLayout(tile45);
        tile45.setLayout(tile45Layout);
        tile45Layout.setHorizontalGroup(
            tile45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile45Layout.setVerticalGroup(
            tile45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile43.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile43Layout = new javax.swing.GroupLayout(tile43);
        tile43.setLayout(tile43Layout);
        tile43Layout.setHorizontalGroup(
            tile43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile43Layout.setVerticalGroup(
            tile43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile41.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile41Layout = new javax.swing.GroupLayout(tile41);
        tile41.setLayout(tile41Layout);
        tile41Layout.setHorizontalGroup(
            tile41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile41Layout.setVerticalGroup(
            tile41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile40.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile40Layout = new javax.swing.GroupLayout(tile40);
        tile40.setLayout(tile40Layout);
        tile40Layout.setHorizontalGroup(
            tile40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile40Layout.setVerticalGroup(
            tile40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile44.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile44Layout = new javax.swing.GroupLayout(tile44);
        tile44.setLayout(tile44Layout);
        tile44Layout.setHorizontalGroup(
            tile44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile44Layout.setVerticalGroup(
            tile44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile42.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile42Layout = new javax.swing.GroupLayout(tile42);
        tile42.setLayout(tile42Layout);
        tile42Layout.setHorizontalGroup(
            tile42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile42Layout.setVerticalGroup(
            tile42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile55.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile55Layout = new javax.swing.GroupLayout(tile55);
        tile55.setLayout(tile55Layout);
        tile55Layout.setHorizontalGroup(
            tile55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile55Layout.setVerticalGroup(
            tile55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile53.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile53Layout = new javax.swing.GroupLayout(tile53);
        tile53.setLayout(tile53Layout);
        tile53Layout.setHorizontalGroup(
            tile53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile53Layout.setVerticalGroup(
            tile53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile51.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile51Layout = new javax.swing.GroupLayout(tile51);
        tile51.setLayout(tile51Layout);
        tile51Layout.setHorizontalGroup(
            tile51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile51Layout.setVerticalGroup(
            tile51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile50.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile50Layout = new javax.swing.GroupLayout(tile50);
        tile50.setLayout(tile50Layout);
        tile50Layout.setHorizontalGroup(
            tile50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile50Layout.setVerticalGroup(
            tile50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile54.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile54Layout = new javax.swing.GroupLayout(tile54);
        tile54.setLayout(tile54Layout);
        tile54Layout.setHorizontalGroup(
            tile54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile54Layout.setVerticalGroup(
            tile54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile52.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile52Layout = new javax.swing.GroupLayout(tile52);
        tile52.setLayout(tile52Layout);
        tile52Layout.setHorizontalGroup(
            tile52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile52Layout.setVerticalGroup(
            tile52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile60.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile60Layout = new javax.swing.GroupLayout(tile60);
        tile60.setLayout(tile60Layout);
        tile60Layout.setHorizontalGroup(
            tile60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile60Layout.setVerticalGroup(
            tile60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile63.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile63Layout = new javax.swing.GroupLayout(tile63);
        tile63.setLayout(tile63Layout);
        tile63Layout.setHorizontalGroup(
            tile63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile63Layout.setVerticalGroup(
            tile63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile64.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile64Layout = new javax.swing.GroupLayout(tile64);
        tile64.setLayout(tile64Layout);
        tile64Layout.setHorizontalGroup(
            tile64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile64Layout.setVerticalGroup(
            tile64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile65.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile65Layout = new javax.swing.GroupLayout(tile65);
        tile65.setLayout(tile65Layout);
        tile65Layout.setHorizontalGroup(
            tile65Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile65Layout.setVerticalGroup(
            tile65Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile61.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile61Layout = new javax.swing.GroupLayout(tile61);
        tile61.setLayout(tile61Layout);
        tile61Layout.setHorizontalGroup(
            tile61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile61Layout.setVerticalGroup(
            tile61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tile62.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile62Layout = new javax.swing.GroupLayout(tile62);
        tile62.setLayout(tile62Layout);
        tile62Layout.setHorizontalGroup(
            tile62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile62Layout.setVerticalGroup(
            tile62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        p1Name.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        p1Name.setForeground(new java.awt.Color(255, 255, 255));
        p1Name.setText("Player 1");

        p2Name.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        p2Name.setForeground(new java.awt.Color(255, 255, 255));
        p2Name.setText("Player 2");

        p1Score.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        p1Score.setForeground(new java.awt.Color(255, 255, 255));
        p1Score.setText("0");

        p2Score.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        p2Score.setForeground(new java.awt.Color(255, 255, 255));
        p2Score.setText("0");

        tile00.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout tile00Layout = new javax.swing.GroupLayout(tile00);
        tile00.setLayout(tile00Layout);
        tile00Layout.setHorizontalGroup(
            tile00Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tile00Layout.setVerticalGroup(
            tile00Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        play0.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        play0.setText("V");
        play0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                play0ActionPerformed(evt);
            }
        });

        play1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        play1.setText("V");
        play1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                play1ActionPerformed(evt);
            }
        });

        play2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        play2.setText("V");
        play2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                play2ActionPerformed(evt);
            }
        });

        play3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        play3.setText("V");
        play3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                play3ActionPerformed(evt);
            }
        });

        play4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        play4.setText("V");
        play4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                play4ActionPerformed(evt);
            }
        });

        play5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        play5.setText("V");
        play5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                play5ActionPerformed(evt);
            }
        });

        play6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        play6.setText("V");
        play6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                play6ActionPerformed(evt);
            }
        });

        p1Score1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        p1Score1.setForeground(new java.awt.Color(255, 255, 255));
        p1Score1.setText("CPU:");

        p1Score2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        p1Score2.setForeground(new java.awt.Color(255, 255, 255));
        p1Score2.setText("CPU:");

        CPU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPU1ActionPerformed(evt);
            }
        });

        CPU2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPU2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Restart");

        p1Score3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        p1Score3.setForeground(new java.awt.Color(255, 255, 255));
        p1Score3.setText("CPU thinktime:");

        cpuThink.setText("0");

        cpuIterations.setText("1");
        cpuIterations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpuIterationsActionPerformed(evt);
            }
        });

        p1Score4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        p1Score4.setForeground(new java.awt.Color(255, 255, 255));
        p1Score4.setText("Max Iterations:");

        p1Score5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        p1Score5.setForeground(new java.awt.Color(255, 255, 255));
        p1Score5.setText("Random?");

        Random2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Random2ActionPerformed(evt);
            }
        });

        Random1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Random1ActionPerformed(evt);
            }
        });

        p1Score6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        p1Score6.setForeground(new java.awt.Color(255, 255, 255));
        p1Score6.setText("Random?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tile05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(play0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tile15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(play1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tile25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(play2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tile35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(play3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tile45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(play4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tile55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tile50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(play5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(tile60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(p1Score5)
                                .addGap(18, 18, 18)
                                .addComponent(Random2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tile62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tile63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(p1Score3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cpuThink, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p1Score4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cpuIterations, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tile65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(p1Score6)
                                .addGap(18, 18, 18)
                                .addComponent(Random1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tile61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p2Name)
                                    .addComponent(p2Score)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p1Score2)
                                        .addGap(18, 18, 18)
                                        .addComponent(CPU2))))
                            .addComponent(play6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tile64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p1Score1)
                                        .addGap(18, 18, 18)
                                        .addComponent(CPU1))
                                    .addComponent(p1Name)
                                    .addComponent(p1Score))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(play0)
                    .addComponent(play1)
                    .addComponent(play2)
                    .addComponent(play3)
                    .addComponent(play4)
                    .addComponent(play5)
                    .addComponent(play6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tile05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tile65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(p1Score6)
                                .addComponent(Random1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tile64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(p1Name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p1Score)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CPU1)
                                    .addComponent(p1Score1))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tile63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tile62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(p1Score4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cpuIterations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p1Score3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cpuThink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tile61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p1Score2)
                                    .addComponent(CPU2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p2Score)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p2Name))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tile55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tile15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tile25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tile35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tile45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tile00, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tile10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tile20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tile30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tile40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tile60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tile50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(p1Score5)
                    .addComponent(Random2)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //function to play a piece in the specified column for the current player
    public void buttonClick(int column)
    {
        boolean success = false;
        int win = -1;
        if(controller.getPlayer())
        {
            if(controller.getBoard().makePlay(column, Integer.valueOf(controller.getPlayer1().getPiece())))
            {
                //successfully made play
                success = true;
                //System.out.println("Play successful");
                
                win = controller.getBoard().checkWin();
                //p1 wins
                if(win == 1)
                {
                    p1Score.setText(String.valueOf(Integer.valueOf(p1Score.getText()) + 1));
                    controller.getPlayer1().won();
                    controller.getPlayer2().lost();
                    controller.reset();
                    //System.out.println("reset() called from win == 1");
                }
                //p2 wins
                else if(win == 2)
                {
                    controller.getPlayer2().won();
                    controller.getPlayer1().lost();
                    p2Score.setText(String.valueOf(Integer.valueOf(p2Score.getText()) + 1));
                    controller.reset();
                    //System.out.println("reset() called from win == 2");
                }
                //draw
                else if(win == 0)
                {
                    controller.getPlayer1().drew();
                    controller.getPlayer2().drew();
                    controller.reset();
                    //System.out.println("reset() called from win == 0");
                }
            }
            else
            {
                //error, failed to make the play
            }
        }
        else
        {
            if(controller.getBoard().makePlay(column, Integer.valueOf(controller.getPlayer2().getPiece())))
            {
                //successfully made play
                success = true;
                //System.out.println("Play successful");
                win = controller.getBoard().checkWin();
                //p1 wins
                if(win == 1)
                {
                    controller.getPlayer1().won();
                    controller.getPlayer2().lost();
                    p1Score.setText(String.valueOf(Integer.valueOf(p1Score.getText()) + 1));
                    controller.reset();
                    //System.out.println("reset() called from win == 1");
                }
                //p2 wins
                else if(win == 2)
                {
                    controller.getPlayer2().won();
                    controller.getPlayer1().lost();
                    p2Score.setText(String.valueOf(Integer.valueOf(p2Score.getText()) + 1));
                    controller.reset();
                    //System.out.println("reset() called from win == 2");
                }
                //draw
                else if(win == 0)
                {
                    controller.getPlayer1().drew();
                    controller.getPlayer2().drew();
                    controller.reset();
                    //System.out.println("reset() called from win == 0");
                }
            }
            else
            {
                //error, failed to make play
            }
        }
        
        if(success)
        {
            prepMove(win);
        }
    }
    
    private void prepMove(int win)
    {
        controller.switchPlayer();

        //System.out.println("player1? : " + ConnectAI.getPlayer() +  ", player1ai? : " + ConnectAI.getPlayer1().ai + ", player2ai? : " + ConnectAI.getPlayer2().ai);

        if(controller.getPlayer() && controller.getPlayer1().ai && !controller.getPlayer2().ai)
        {
            //System.out.println("Sent player 1 to takeTurn()");
            controller.getPlayer1().takeTurn(controller.getBoard().getBoard());
        }
        else if(!controller.getPlayer() && !controller.getPlayer1().ai && controller.getPlayer2().ai)
        {
            //System.out.println("Sent player 2 to takeTurn()");
            controller.getPlayer2().takeTurn(controller.getBoard().getBoard());
        }
    }
    
    private void play0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_play0ActionPerformed
        buttonClick(0);
    }//GEN-LAST:event_play0ActionPerformed

    private void play1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_play1ActionPerformed
        buttonClick(1);
    }//GEN-LAST:event_play1ActionPerformed

    private void play2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_play2ActionPerformed
        buttonClick(2);
    }//GEN-LAST:event_play2ActionPerformed

    private void play3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_play3ActionPerformed
        buttonClick(3);
    }//GEN-LAST:event_play3ActionPerformed

    private void play4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_play4ActionPerformed
        buttonClick(4);
    }//GEN-LAST:event_play4ActionPerformed

    private void play5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_play5ActionPerformed
        buttonClick(5);
    }//GEN-LAST:event_play5ActionPerformed

    private void play6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_play6ActionPerformed
        buttonClick(6);
    }//GEN-LAST:event_play6ActionPerformed

    private void CPU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPU1ActionPerformed
        controller.changeSettings(CPU1.isSelected(), CPU2.isSelected(), Integer.valueOf(cpuIterations.getText()));
    }//GEN-LAST:event_CPU1ActionPerformed

    private void CPU2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPU2ActionPerformed
        controller.changeSettings(CPU1.isSelected(), CPU2.isSelected(), Integer.valueOf(cpuIterations.getText()));
    }//GEN-LAST:event_CPU2ActionPerformed

    private void cpuIterationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpuIterationsActionPerformed
        controller.changeSettings(CPU1.isSelected(), CPU2.isSelected(), Integer.valueOf(cpuIterations.getText()));
    }//GEN-LAST:event_cpuIterationsActionPerformed

    private void Random2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Random2ActionPerformed
        controller.random2(CPU2.isSelected());
    }//GEN-LAST:event_Random2ActionPerformed

    private void Random1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Random1ActionPerformed
        controller.random1(CPU1.isSelected());
    }//GEN-LAST:event_Random1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CPU1;
    private javax.swing.JCheckBox CPU2;
    private javax.swing.JCheckBox Random1;
    private javax.swing.JCheckBox Random2;
    private javax.swing.JTextField cpuIterations;
    private javax.swing.JTextField cpuThink;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel p1Name;
    private javax.swing.JLabel p1Score;
    private javax.swing.JLabel p1Score1;
    private javax.swing.JLabel p1Score2;
    private javax.swing.JLabel p1Score3;
    private javax.swing.JLabel p1Score4;
    private javax.swing.JLabel p1Score5;
    private javax.swing.JLabel p1Score6;
    private javax.swing.JLabel p2Name;
    private javax.swing.JLabel p2Score;
    private javax.swing.JButton play0;
    private javax.swing.JButton play1;
    private javax.swing.JButton play2;
    private javax.swing.JButton play3;
    private javax.swing.JButton play4;
    private javax.swing.JButton play5;
    private javax.swing.JButton play6;
    private javax.swing.JPanel tile00;
    private javax.swing.JPanel tile01;
    private javax.swing.JPanel tile02;
    private javax.swing.JPanel tile03;
    private javax.swing.JPanel tile04;
    private javax.swing.JPanel tile05;
    private javax.swing.JPanel tile10;
    private javax.swing.JPanel tile11;
    private javax.swing.JPanel tile12;
    private javax.swing.JPanel tile13;
    private javax.swing.JPanel tile14;
    private javax.swing.JPanel tile15;
    private javax.swing.JPanel tile20;
    private javax.swing.JPanel tile21;
    private javax.swing.JPanel tile22;
    private javax.swing.JPanel tile23;
    private javax.swing.JPanel tile24;
    private javax.swing.JPanel tile25;
    private javax.swing.JPanel tile30;
    private javax.swing.JPanel tile31;
    private javax.swing.JPanel tile32;
    private javax.swing.JPanel tile33;
    private javax.swing.JPanel tile34;
    private javax.swing.JPanel tile35;
    private javax.swing.JPanel tile40;
    private javax.swing.JPanel tile41;
    private javax.swing.JPanel tile42;
    private javax.swing.JPanel tile43;
    private javax.swing.JPanel tile44;
    private javax.swing.JPanel tile45;
    private javax.swing.JPanel tile50;
    private javax.swing.JPanel tile51;
    private javax.swing.JPanel tile52;
    private javax.swing.JPanel tile53;
    private javax.swing.JPanel tile54;
    private javax.swing.JPanel tile55;
    private javax.swing.JPanel tile60;
    private javax.swing.JPanel tile61;
    private javax.swing.JPanel tile62;
    private javax.swing.JPanel tile63;
    private javax.swing.JPanel tile64;
    private javax.swing.JPanel tile65;
    // End of variables declaration//GEN-END:variables
}
